server:
  port: 9001

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/study_security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: com.example.oauth2.sso.web.entities

security:
  oauth2:
    client:
      client-id: client1 # 当前客户端id
      client-secret: mengxuegu-secret # 客户端的密码
      user-authorization-uri: http://localhost:8090/auth/oauth/authorize #请求认证的地址，获取授权码地址
      access-token-uri: http://localhost:8090/auth/oauth/token # 请求令牌的地址
    resource:
      jwt:
        # 当用户授权之后会响应一个授权码，重定向到当前应用的 http://localhost:9001/login?code=xxx
        # 自动的会对 /login 去获取令牌，获取到令牌后会通过 key-uri 获取到的公钥进行解密然后本地身份认证和授权（Session）
        key-uri: http://localhost:8090/auth/oauth/token_key # 获取公钥

# 日志级别，会打印sql语句
logging:
  level:
    com.example.web.mapper: debug